# 服务器配置
server:
# 服务器端口
  port: 80

# 服务器编码格式

# 全局Debug模式
debug: false

spring:
  http:
    encoding:
      charset: utf-8
  cache:
    type: redis

  redis:
    defaultexpirationtime: 300

# 解决产生多数据源的问题
  data:
    redis:
      repositories:
        enabled: false

#  thymeleaf:

  # 模板路径前缀
#    prefix: classpath:/templates/
  # 模板路径后缀
#    suffix: .html
  # 是否开启模板缓存（测试环境不开启）
#    cache: false
  # 使用非严格解析的HTML5格式（需要添加NekoHTML库依赖）
#    mode: HTML5


# 静态资源配置
  mvc:
    static-path-pattern: /**

    # 不使用页面标签默认ICO图标

#    favicon:
#      enabled: true
#  resources:
#    static-locations: classpath:/static/,classpath:/public/,classpath:/templates/,classpath:/resources/,classpath:/META-INF/resources/

#   数据源配置

  datasource:

    # 驱动配置信息
    # 驱动类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 驱动名
    driver-class-name: com.mysql.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/demo
    # 数据库用户登录名
    username: root
    # 数据库用户登录密码
    password: 40010

  # Druid连接池配置
    druid:
      # 初始化连接数大小
      initial-size: 10
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接等待超时时间（单位：毫秒）
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接（单位：毫秒）
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间（单位：毫秒）
      min-evictable-idle-time-millis: 30000
      # 定义数据库查询测试语句
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      stat-view-servlet:
        login-username: admin
        login-password: admin

# 控制台多彩输出
  output:
    ansi:
      enabled: detect
# 解决延迟加载序列化的问题
  jackson:
    serialization: {FAIL_ON_EMPTY_BEANS : false}

# mybatis配置
#mybatis:
#  mapper-locations: classpath:MapperFile/*.xml
#  type-aliases-package: loclhost.model

# 分页插件
pagehelper:
  reasonable: true
  params: count=countSql
  helper-dialect: mysql
  offset-as-page-num: true

#mapper:
#    not-empty: true

# logback日志配置
logging:
# 设置文件，可以是绝对路径，也可以是相对路径。
# file: /log.log
# 设置目录，会在该目录下创建spring.log文件，并写入日志内容
# path: /logFile
 level.com.mapper: debug

shiro:
  passwordsecret: mock

  jwt:
# 签名密钥
    secret: abc
# token有校时间（秒）
    accesstokenexpireTime: 60
# token刷新有校时间（秒）
    refreshtokenexpireTime: 3600

